name: fineopay_psp
description: Official Flutter SDK for FineoPay PSP API (Payments, Transfers, Transactions).
version: 1.0.1

homepage: https://fineopay.com
repository: https://github.com/upya-innov/fineopay_psp
issue_tracker: https://github.com/upya-innov/fineopay_psp/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

topics:
  - payments
  - fintech
  - mobile-money
  - flutter
